package db

import (
	"context"
	"testing"
	"time"


	"github.com/mybank/utils"
	"github.com/stretchr/testify/require"
)


func CreateRandomTransfer(t *testing.T) Transfer {
	account1 := CreateRandomAccount(t)
	account2 := CreateRandomAccount(t)

	arg := CreateTransfersParams{
		FromAccountID: account1.ID,
		ToAccountID:   account2.ID,
		Amount:        utils.RandomInt(1, 1000),
	}
	transfer, err := testQueries.CreateTransfers(context.Background(), arg)
	require.NoError(t, err)
	require.NotEmpty(t, transfer)

	require.Equal(t, arg.FromAccountID, transfer.FromAccountID)
	require.Equal(t, arg.ToAccountID, transfer.ToAccountID)
	require.Equal(t, arg.Amount, transfer.Amount)
	require.NotZero(t, transfer.ID)
	require.NotZero(t, transfer.CreatedAt)

	return transfer
}

func TestTransfer(t *testing.T) {
	CreateRandomTransfer(t)
}


func TestGetTransfer(t *testing.T) {
	transfer1 := CreateRandomTransfer(t)

	transfer2, err := testQueries.GetTransfer(context.Background(), transfer1.ID)
	require.NoError(t, err)
	require.NotEmpty(t, transfer2)

	require.Equal(t, transfer1.ID, transfer2.ID)
	require.Equal(t, transfer1.FromAccountID, transfer2.FromAccountID)
	require.Equal(t, transfer1.ToAccountID, transfer2.ToAccountID)
	require.Equal(t, transfer1.Amount, transfer2.Amount)
	require.WithinDuration(t, transfer1.CreatedAt, transfer2.CreatedAt, time.Second)
}

// func TestListTransfer(t *testing.T) {
// 	account1 := CreateRandomAccount(t)
// 	account2 := CreateRandomAccount(t)

// 	for i := 0; i < 10; i++ {
// 		CreateRandomTransfer(t)
// 	}

// 	arg := listTransferParams{
// 		FromAccountID: account1.ID,
// 		Limit:  5,
// 		Offset: 5,
// 	}

// 	transfers, err := testQueries.listTransfer(context.Background(), arg)
// 	require.NoError(t, err)
// 	require.Len(t, transfers, 5)


// 	for _, transfer := range transfers {
// 		require.NotEmpty(t, transfer)
// 		require.Equal(t, account1.ID, transfer.FromAccountID)
// 		require.Equal(t, account2.ID, transfer.ToAccountID)
// 	}
// }

func TestListTransfer(t *testing.T) {
	account1 := CreateRandomAccount(t)
	account2 := CreateRandomAccount(t)

	// Create 10 transfers from account1 → account2
	for i := 0; i < 10; i++ {
		arg := CreateTransfersParams{
			FromAccountID: account1.ID,
			ToAccountID:   account2.ID,
			Amount:        utils.RandomInt(1, 1000),
		}
		_, err := testQueries.CreateTransfers(context.Background(), arg)
		require.NoError(t, err)
	}

	arg := listTransferParams{ // Use the actual name generated by sqlc (case-sensitive!)
		FromAccountID: account1.ID,
		Limit:         5,
		Offset:        0,
	}

	transfers, err := testQueries.listTransfer(context.Background(), arg)
	require.NoError(t, err)
	require.Len(t, transfers, 5)

	for _, transfer := range transfers {
		require.NotEmpty(t, transfer)
		require.Equal(t, account1.ID, transfer.FromAccountID)
	}
}
